___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Topic Modeling Assessment Project

Welcome to your Topic Modeling Assessment! For this project you will be working with a dataset of over 400,000 quora questions that have no labeled cateogry, and attempting to find 20 cateogries to assign these questions to. The .csv file of these text questions can be found underneath the Topic-Modeling folder.

Remember you can always check the solutions notebook and video lecture for any questions.

#### Task: Import pandas and read in the quora_questions.csv file.

In [5]:
import numpy as np
import pandas as pd

df_quora = pd.read_csv('quora_questions.csv')
display(df_quora[:3])

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...

# Preprocessing

#### Task: Use TF-IDF Vectorization to create a vectorized document term matrix. You may want to explore the max_df and min_df parameters.

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.9, min_df=2, stop_words='english')
dtm = tfidf.fit_transform(df_quora['Question'])
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

# Non-negative Matrix Factorization

#### TASK: Using Scikit-Learn create an instance of NMF with 20 expected components. (Use random_state=42)..

In [32]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=20, random_state=42)
nmf.fit(dtm)
nmf

C:\Users\Dev\anaconda3\envs\KSDS_Bootcamp\Lib\site-packages\sklearn\decomposition\_nmf.py:1770: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


NMF(n_components=20, random_state=42)

In [43]:
display(len(nmf.components_), type(nmf.components_), nmf.components_.shape, nmf.components_[:3])

20

numpy.ndarray

(20, 38669)

array([[0.00000000e+00, 5.65092701e-02, 5.42127292e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.24553666e-03, 0.00000000e+00, 3.47094202e-05, ...,
        0.00000000e+00, 3.66959931e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [65]:
first_topic = nmf.components_[0]
display(first_topic.argsort())
display([tfidf.get_feature_names_out()[i] for i in first_topic.argsort()[-10:]])

array([    0, 22613, 22611, ...,  5268, 22925,  4632], dtype=int64)

['phone',
 'buy',
 'laptop',
 'movie',
 'ways',
 '2016',
 'books',
 'book',
 'movies',
 'best']

#### TASK: Print our the top 15 most common words for each of the 20 topics.

In [83]:
for index in range(len(nmf.components_)):
    topic = nmf.components_[index]
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print('\n')

['phone', 'buy', 'laptop', 'movie', 'ways', '2016', 'books', 'book', 'movies', 'best']


['use', 'exist', 'really', 'compare', 'cost', 'long', 'feel', 'work', 'mean', 'does']


['improvement', 'delete', 'asked', 'google', 'answers', 'answer', 'ask', 'question', 'questions', 'quora']


['internet', 'free', 'home', 'easy', 'youtube', 'ways', 'earn', 'online', 'make', 'money']


['live', 'want', 'change', 'moment', 'real', 'important', 'thing', 'meaning', 'purpose', 'life']


['china', 'business', 'country', 'olympics', 'available', 'job', 'spotify', 'war', 'pakistan', 'india']


['hacking', 'want', 'python', 'languages', 'java', 'learning', 'start', 'language', 'programming', 'learn']


['vote', 'better', 'election', 'did', 'win', 'hillary', 'president', 'clinton', 'donald', 'trump']


['place', 'pakistan', 'happen', 'end', 'country', 'iii', 'start', 'did', 'war', 'world']


['culture', 'women', 'work', 'girls', 'live', 'girl', 'look', 'sex', 'feel', 'like']


['business', 'read', 'start

#### TASK: Add a new column to the original quora dataframe that labels each question into one of the 20 topic categories.

In [96]:
topic_results = nmf.transform(dtm)
display(len(topic_results), type(topic_results), topic_results.shape, topic_results[:3])

404289

numpy.ndarray

(404289, 20)

array([[2.74927015e-04, 5.88014577e-05, 6.17412189e-06, 4.95620733e-04,
        3.93020250e-05, 2.61336884e-02, 3.90468377e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.33820194e-04, 1.15818171e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.97335523e-04,
        0.00000000e+00, 6.97429434e-04, 2.13458466e-04, 0.00000000e+00],
       [1.95705655e-04, 8.80743307e-05, 0.00000000e+00, 0.00000000e+00,
        1.64358496e-04, 5.64039787e-05, 0.00000000e+00, 0.00000000e+00,
        1.87920498e-05, 0.00000000e+00, 1.77490994e-04, 6.03725969e-06,
        2.84485878e-05, 1.92113334e-04, 0.00000000e+00, 0.00000000e+00,
        8.30212055e-04, 0.00000000e+00, 5.51003101e-05, 1.05546944e-05],
       [1.77372166e-04, 6.43938862e-04, 1.60463804e-03, 2.36363033e-03,
        1.64476118e-04, 1.88215618e-04, 7.32397532e-05, 0.00000000e+00,
        5.71004847e-05, 0.00000000e+00, 7.82504672e-04, 3.40529878e-04,
        4.64315159e-04, 6.99892986e-04, 7.60307401e-04, 2.1939

In [102]:
df_quora['Topic'] = topic_results.argmax(axis=1)
display(df_quora[:5])

Question  Topic
0  What is the step by step guide to invest in sh...      5
1  What is the story of Kohinoor (Koh-i-Noor) Dia...     16
2  How can I increase the speed of my internet co...     17
3  Why am I mentally very lonely? How can I solve...     11
4  Which one dissolve in water quikly sugar, salt...     14

# Great job!